-- Admin activity archive.
-- Append-only log of important user/system actions.
-- Does not change matching, RLS, offers, reviews, chat,
-- cancellation, public_id, or existing RPC signatures.

create table if not exists public.admin_activity_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_id uuid null,
  actor_role text null,
  event_type text not null,
  entity_type text null,
  entity_id bigint null,
  entity_uuid uuid null,
  job_id bigint null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists admin_activity_events_occurred_at_id_idx
  on public.admin_activity_events (occurred_at desc, id desc);

create index if not exists admin_activity_events_event_type_idx
  on public.admin_activity_events (event_type);

create index if not exists admin_activity_events_actor_id_idx
  on public.admin_activity_events (actor_id);

create index if not exists admin_activity_events_job_id_idx
  on public.admin_activity_events (job_id);

alter table public.admin_activity_events enable row level security;
alter table public.admin_activity_events force row level security;

revoke all on table public.admin_activity_events
  from public, anon, authenticated;

create or replace function public.log_activity_event(
  p_event_type text,
  p_actor_role text default null,
  p_entity_type text default null,
  p_entity_id bigint default null,
  p_entity_uuid uuid default null,
  p_job_id bigint default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_role text;
begin
  if p_event_type is null or btrim(p_event_type) = '' then
    return;
  end if;

  v_actor_role := case
    when p_actor_role in ('customer', 'provider', 'admin', 'system')
      then p_actor_role
    else null
  end;

  if v_actor_role = 'admin' then
    if not exists (
      select 1
      from public.profiles as profile
      where profile.id = v_actor_id
        and profile.is_admin = true
    ) then
      return;
    end if;
  end if;

  if v_actor_role = 'system' then
    v_actor_id := null;
  end if;

  insert into public.admin_activity_events (
    actor_id,
    actor_role,
    event_type,
    entity_type,
    entity_id,
    entity_uuid,
    job_id,
    metadata
  ) values (
    v_actor_id,
    v_actor_role,
    btrim(p_event_type),
    p_entity_type,
    p_entity_id,
    p_entity_uuid,
    p_job_id,
    coalesce(p_metadata, '{}'::jsonb)
  );
exception
  when others then
    raise warning 'log_activity_event failed: %', sqlerrm;
end;
$$;

revoke all on function public.log_activity_event(
  text, text, text, bigint, uuid, bigint, jsonb
) from public, anon, authenticated;

create or replace function public.admin_activity_log_jobs()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.log_activity_event(
      'job.created',
      'customer',
      'job',
      new.id,
      null,
      new.id,
      jsonb_build_object('status', new.status)
    );
    return new;
  end if;

  if old.status is distinct from new.status then
    if new.status = 'cancelled' then
      perform public.log_activity_event(
        'job.cancelled',
        'customer',
        'job',
        new.id,
        null,
        new.id,
        jsonb_build_object(
          'from_status', old.status,
          'to_status', new.status,
          'cancellation_reason', new.cancellation_reason
        )
      );
    elsif new.status = 'completed' then
      perform public.log_activity_event(
        'job.completed',
        'customer',
        'job',
        new.id,
        null,
        new.id,
        jsonb_build_object(
          'from_status', old.status,
          'to_status', new.status
        )
      );
    end if;

    return new;
  end if;

  if old.title is distinct from new.title
    or old.description is distinct from new.description
    or old.budget is distinct from new.budget
    or old.city is distinct from new.city
    or old.location_type is distinct from new.location_type
    or old.deadline is distinct from new.deadline
    or old.service_id is distinct from new.service_id
  then
    perform public.log_activity_event(
      'job.updated',
      'customer',
      'job',
      new.id,
      null,
      new.id,
      jsonb_build_object('status', new.status)
    );
  end if;

  return new;
exception
  when others then
    raise warning 'admin_activity_log_jobs failed: %', sqlerrm;
    return new;
end;
$$;

drop trigger if exists admin_activity_log_jobs_insert on public.jobs;
create trigger admin_activity_log_jobs_insert
  after insert on public.jobs
  for each row
  execute procedure public.admin_activity_log_jobs();

drop trigger if exists admin_activity_log_jobs_update on public.jobs;
create trigger admin_activity_log_jobs_update
  after update on public.jobs
  for each row
  execute procedure public.admin_activity_log_jobs();

create or replace function public.admin_activity_log_offers()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.log_activity_event(
      'offer.created',
      'provider',
      'offer',
      new.id,
      null,
      new.job_id,
      jsonb_build_object('status', new.status)
    );
    return new;
  end if;

  if old.status is not distinct from new.status then
    return new;
  end if;

  if new.status = 'accepted' then
    perform public.log_activity_event(
      'offer.accepted',
      'customer',
      'offer',
      new.id,
      null,
      new.job_id,
      jsonb_build_object(
        'from_status', old.status,
        'to_status', new.status
      )
    );
  elsif new.status = 'rejected' then
    perform public.log_activity_event(
      'offer.rejected',
      'customer',
      'offer',
      new.id,
      null,
      new.job_id,
      jsonb_build_object(
        'from_status', old.status,
        'to_status', new.status
      )
    );
  end if;

  return new;
exception
  when others then
    raise warning 'admin_activity_log_offers failed: %', sqlerrm;
    return new;
end;
$$;

drop trigger if exists admin_activity_log_offers_insert on public.offers;
create trigger admin_activity_log_offers_insert
  after insert on public.offers
  for each row
  execute procedure public.admin_activity_log_offers();

drop trigger if exists admin_activity_log_offers_update on public.offers;
create trigger admin_activity_log_offers_update
  after update on public.offers
  for each row
  execute procedure public.admin_activity_log_offers();

create or replace function public.admin_activity_log_reviews()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_role text;
begin
  v_actor_role := case
    when new.reviewer_role in ('customer', 'provider') then new.reviewer_role
    else null
  end;

  if tg_op = 'INSERT' then
    if new.skipped then
      perform public.log_activity_event(
        'review.skipped',
        v_actor_role,
        'review',
        new.id,
        null,
        new.job_id,
        jsonb_build_object('skipped', true)
      );
    else
      perform public.log_activity_event(
        'review.submitted',
        v_actor_role,
        'review',
        new.id,
        null,
        new.job_id,
        jsonb_build_object(
          'skipped', false,
          'rating', new.rating
        )
      );
    end if;
  end if;

  if tg_op = 'UPDATE'
    and old.published_at is null
    and new.published_at is not null
  then
    perform public.log_activity_event(
      'review.published',
      v_actor_role,
      'review',
      new.id,
      null,
      new.job_id,
      jsonb_build_object('skipped', new.skipped)
    );
  end if;

  return new;
exception
  when others then
    raise warning 'admin_activity_log_reviews failed: %', sqlerrm;
    return new;
end;
$$;

drop trigger if exists admin_activity_log_reviews_insert on public.reviews;
create trigger admin_activity_log_reviews_insert
  after insert on public.reviews
  for each row
  execute procedure public.admin_activity_log_reviews();

drop trigger if exists admin_activity_log_reviews_update on public.reviews;
create trigger admin_activity_log_reviews_update
  after update on public.reviews
  for each row
  execute procedure public.admin_activity_log_reviews();

create or replace function public.admin_activity_log_messages()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_job_id bigint;
  v_actor_role text;
begin
  select conversation_job.job_id
  into v_job_id
  from public.conversation_jobs as conversation_job
  where conversation_job.conversation_id = new.conversation_id
  order by conversation_job.created_at desc
  limit 1;

  select case
    when job.customer_id = new.sender_id then 'customer'
    else 'provider'
  end
  into v_actor_role
  from public.jobs as job
  where job.id = v_job_id;

  perform public.log_activity_event(
    'message.sent',
    v_actor_role,
    'message',
    new.id,
    null,
    v_job_id,
    jsonb_build_object(
      'conversation_id', new.conversation_id,
      'content_length', char_length(coalesce(new.message, '')),
      'job_id', v_job_id
    )
  );

  return new;
exception
  when others then
    raise warning 'admin_activity_log_messages failed: %', sqlerrm;
    return new;
end;
$$;

drop trigger if exists admin_activity_log_messages_insert on public.messages;
create trigger admin_activity_log_messages_insert
  after insert on public.messages
  for each row
  execute procedure public.admin_activity_log_messages();

create or replace function public.admin_activity_log_profiles()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_is_admin boolean := false;
  v_flags_changed boolean := false;
begin
  if old.full_name is distinct from new.full_name then
    perform public.log_activity_event(
      'profile.name_updated',
      case
        when new.provider_enabled and not new.customer_enabled then 'provider'
        else 'customer'
      end,
      'profile',
      null,
      new.id,
      null,
      '{}'::jsonb
    );
  end if;

  v_flags_changed :=
    old.customer_enabled is distinct from new.customer_enabled
    or old.provider_enabled is distinct from new.provider_enabled
    or old.is_admin is distinct from new.is_admin;

  if not v_flags_changed then
    return new;
  end if;

  select coalesce(profile.is_admin, false)
  into v_actor_is_admin
  from public.profiles as profile
  where profile.id = v_actor_id;

  if v_actor_is_admin
    and (
      v_actor_id is distinct from new.id
      or old.is_admin is distinct from new.is_admin
    )
  then
    perform public.log_activity_event(
      'admin.permissions_updated',
      'admin',
      'admin',
      null,
      new.id,
      null,
      jsonb_build_object(
        'target_user_id', new.id,
        'customer_enabled', new.customer_enabled,
        'provider_enabled', new.provider_enabled,
        'is_admin', new.is_admin
      )
    );
  elsif v_actor_id = new.id
    and (
      old.customer_enabled is distinct from new.customer_enabled
      or old.provider_enabled is distinct from new.provider_enabled
    )
  then
    perform public.log_activity_event(
      'profile.account_type_changed',
      case
        when new.provider_enabled and not new.customer_enabled then 'provider'
        else 'customer'
      end,
      'profile',
      null,
      new.id,
      null,
      jsonb_build_object(
        'customer_enabled', new.customer_enabled,
        'provider_enabled', new.provider_enabled
      )
    );
  end if;

  return new;
exception
  when others then
    raise warning 'admin_activity_log_profiles failed: %', sqlerrm;
    return new;
end;
$$;

drop trigger if exists admin_activity_log_profiles_update on public.profiles;
create trigger admin_activity_log_profiles_update
  after update on public.profiles
  for each row
  execute procedure public.admin_activity_log_profiles();

create or replace function public.admin_list_activity_events(
  p_limit integer default 50,
  p_offset integer default 0,
  p_event_type text default null,
  p_actor_id uuid default null,
  p_job_id bigint default null
)
returns table (
  id bigint,
  occurred_at timestamptz,
  actor_id uuid,
  actor_role text,
  actor_name text,
  event_type text,
  entity_type text,
  entity_id bigint,
  entity_uuid uuid,
  job_id bigint,
  job_title text,
  job_public_id uuid,
  metadata jsonb
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  v_limit integer;
  v_offset integer;
begin
  if current_user_id is null then
    raise exception 'Giriş yapmalısın.';
  end if;

  if not exists (
    select 1
    from public.profiles as profile
    where profile.id = current_user_id
      and profile.is_admin = true
  ) then
    raise exception 'Bu işlem için admin yetkisi gerekir.';
  end if;

  v_limit := least(greatest(coalesce(p_limit, 50), 1), 100);
  v_offset := greatest(coalesce(p_offset, 0), 0);

  return query
  select
    event.id,
    event.occurred_at,
    event.actor_id,
    event.actor_role,
    nullif(btrim(actor.full_name), ''),
    event.event_type,
    event.entity_type,
    event.entity_id,
    event.entity_uuid,
    event.job_id,
    job.title,
    job.public_id,
    event.metadata
  from public.admin_activity_events as event
  left join public.profiles as actor
    on actor.id = event.actor_id
  left join public.jobs as job
    on job.id = event.job_id
  where (
      p_event_type is null
      or btrim(p_event_type) = ''
      or event.event_type = btrim(p_event_type)
    )
    and (
      p_actor_id is null
      or event.actor_id = p_actor_id
    )
    and (
      p_job_id is null
      or event.job_id = p_job_id
    )
  order by event.occurred_at desc, event.id desc
  limit v_limit
  offset v_offset;
end;
$$;

revoke all on function public.admin_list_activity_events(
  integer, integer, text, uuid, bigint
) from public, anon;

grant execute on function public.admin_list_activity_events(
  integer, integer, text, uuid, bigint
) to authenticated;
