-- Per-admin unread support tickets + admin notifications on create.
-- Does not change user Support RLS, messaging, jobs, or activity event types.

create table if not exists public.admin_support_ticket_reads (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null
    references public.admin_support_tickets (id)
    on delete cascade,
  admin_id uuid not null
    references public.profiles (id)
    on delete cascade,
  read_at timestamptz not null default now(),
  constraint admin_support_ticket_reads_ticket_admin_key
    unique (ticket_id, admin_id)
);

create index if not exists admin_support_ticket_reads_admin_id_read_at_idx
  on public.admin_support_ticket_reads (admin_id, read_at);

create index if not exists admin_support_ticket_reads_ticket_id_idx
  on public.admin_support_ticket_reads (ticket_id);

alter table public.admin_support_ticket_reads enable row level security;
alter table public.admin_support_ticket_reads force row level security;

revoke all on table public.admin_support_ticket_reads
  from public, anon, authenticated;

insert into public.admin_support_ticket_reads (
  ticket_id,
  admin_id,
  read_at
)
select
  ticket.id,
  profile.id,
  now()
from public.admin_support_tickets as ticket
cross join public.profiles as profile
where profile.is_admin = true
on conflict (ticket_id, admin_id) do nothing;

alter table public.notifications
  add column if not exists metadata jsonb not null default '{}'::jsonb;

do $$
declare
  constraint_name text;
begin
  select con.conname
  into constraint_name
  from pg_constraint as con
  where con.conrelid = 'public.notifications'::regclass
    and con.contype = 'c'
    and pg_get_constraintdef(con.oid) ilike '%offer_received%';

  if constraint_name is not null then
    execute format(
      'alter table public.notifications drop constraint %I',
      constraint_name
    );
  end if;
end
$$;

alter table public.notifications
  add constraint notifications_type_check
  check (
    type in (
      'offer_received',
      'offer_accepted',
      'offer_rejected',
      'new_message',
      'project_invitation',
      'job_completed',
      'support_ticket_created'
    )
  );

create or replace function public.admin_mark_support_ticket_read(
  p_ticket_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Giriş yapmalısın.';
  end if;

  if not exists (
    select 1
    from public.profiles as profile
    where profile.id = current_user_id
      and profile.is_admin = true
  ) then
    raise exception 'Bu işlem için admin yetkisi gerekir.';
  end if;

  if p_ticket_id is null or not exists (
    select 1
    from public.admin_support_tickets as ticket
    where ticket.id = p_ticket_id
  ) then
    raise exception 'Destek talebi bulunamadı.';
  end if;

  insert into public.admin_support_ticket_reads (
    ticket_id,
    admin_id,
    read_at
  ) values (
    p_ticket_id,
    current_user_id,
    now()
  )
  on conflict on constraint admin_support_ticket_reads_ticket_admin_key
  do update
  set read_at = now();
end;
$$;

revoke all on function public.admin_mark_support_ticket_read(bigint)
  from public, anon;

grant execute on function public.admin_mark_support_ticket_read(bigint)
  to authenticated;

create or replace function public.admin_get_unread_support_ticket_count()
returns integer
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  v_count integer;
begin
  if current_user_id is null then
    raise exception 'Giriş yapmalısın.';
  end if;

  if not exists (
    select 1
    from public.profiles as profile
    where profile.id = current_user_id
      and profile.is_admin = true
  ) then
    raise exception 'Bu işlem için admin yetkisi gerekir.';
  end if;

  select count(*)::integer
  into v_count
  from public.admin_support_tickets as ticket
  where not exists (
    select 1
    from public.admin_support_ticket_reads as ticket_read
    where ticket_read.ticket_id = ticket.id
      and ticket_read.admin_id = current_user_id
  );

  return coalesce(v_count, 0);
end;
$$;

revoke all on function public.admin_get_unread_support_ticket_count()
  from public, anon;

grant execute on function public.admin_get_unread_support_ticket_count()
  to authenticated;

drop function if exists public.admin_list_support_tickets(
  integer, integer, text, text, text
);

create function public.admin_list_support_tickets(
  p_limit integer default 50,
  p_offset integer default 0,
  p_status text default null,
  p_priority text default null,
  p_category text default null
)
returns table (
  id bigint,
  created_at timestamptz,
  subject text,
  category text,
  priority text,
  status text,
  related_job_id bigint,
  user_id uuid,
  user_name text,
  job_title text,
  job_public_id uuid,
  is_unread boolean
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  v_limit integer;
  v_offset integer;
begin
  if current_user_id is null then
    raise exception 'Giriş yapmalısın.';
  end if;

  if not exists (
    select 1
    from public.profiles as profile
    where profile.id = current_user_id
      and profile.is_admin = true
  ) then
    raise exception 'Bu işlem için admin yetkisi gerekir.';
  end if;

  v_limit := least(greatest(coalesce(p_limit, 50), 1), 100);
  v_offset := greatest(coalesce(p_offset, 0), 0);

  return query
  select
    ticket.id,
    ticket.created_at,
    ticket.subject,
    ticket.category,
    ticket.priority,
    ticket.status,
    ticket.related_job_id,
    ticket.user_id,
    nullif(btrim(profile.full_name), ''),
    job.title,
    job.public_id,
    not exists (
      select 1
      from public.admin_support_ticket_reads as ticket_read
      where ticket_read.ticket_id = ticket.id
        and ticket_read.admin_id = current_user_id
    )
  from public.admin_support_tickets as ticket
  left join public.profiles as profile
    on profile.id = ticket.user_id
  left join public.jobs as job
    on job.id = ticket.related_job_id
  where (
      p_status is null
      or btrim(p_status) = ''
      or ticket.status = btrim(p_status)
    )
    and (
      p_priority is null
      or btrim(p_priority) = ''
      or ticket.priority = btrim(p_priority)
    )
    and (
      p_category is null
      or btrim(p_category) = ''
      or ticket.category = btrim(p_category)
    )
  order by ticket.created_at desc, ticket.id desc
  limit v_limit
  offset v_offset;
end;
$$;

revoke all on function public.admin_list_support_tickets(
  integer, integer, text, text, text
) from public, anon;

grant execute on function public.admin_list_support_tickets(
  integer, integer, text, text, text
) to authenticated;

create or replace function public.create_support_ticket(
  p_subject text,
  p_description text,
  p_category text,
  p_priority text default 'normal',
  p_related_job_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  v_subject text;
  v_description text;
  v_priority text;
  v_actor_role text;
  v_ticket_id bigint;
begin
  if current_user_id is null then
    raise exception 'Giriş yapmalısın.';
  end if;

  v_subject := nullif(btrim(coalesce(p_subject, '')), '');
  v_description := nullif(btrim(coalesce(p_description, '')), '');
  v_priority := coalesce(nullif(btrim(coalesce(p_priority, '')), ''), 'normal');

  if v_subject is null then
    raise exception 'Konu boş olamaz.';
  end if;

  if v_description is null then
    raise exception 'Açıklama boş olamaz.';
  end if;

  if p_category is null or p_category not in (
    'job',
    'offer',
    'messaging',
    'account',
    'payment',
    'technical',
    'other'
  ) then
    raise exception 'Geçerli bir kategori seç.';
  end if;

  if v_priority not in ('low', 'normal', 'high', 'urgent') then
    raise exception 'Geçerli bir öncelik seç.';
  end if;

  if p_related_job_id is not null then
    if not exists (
      select 1
      from public.jobs as job
      where job.id = p_related_job_id
    ) then
      raise exception 'İlgili iş bulunamadı.';
    end if;
  end if;

  insert into public.admin_support_tickets (
    user_id,
    subject,
    description,
    category,
    priority,
    status,
    related_job_id
  ) values (
    current_user_id,
    v_subject,
    v_description,
    p_category,
    v_priority,
    'open',
    p_related_job_id
  )
  returning id into v_ticket_id;

  select case
    when profile.provider_enabled and not profile.customer_enabled then 'provider'
    else 'customer'
  end
  into v_actor_role
  from public.profiles as profile
  where profile.id = current_user_id;

  perform public.log_activity_event(
    'support.ticket_created',
    v_actor_role,
    'support_ticket',
    v_ticket_id,
    null,
    p_related_job_id,
    jsonb_build_object(
      'category', p_category,
      'priority', v_priority,
      'status', 'open'
    )
  );

  begin
    insert into public.notifications (
      user_id,
      type,
      title,
      body,
      href,
      job_id,
      actor_id,
      offer_id,
      conversation_id,
      message_id,
      read_at,
      metadata
    )
    select
      profile.id,
      'support_ticket_created',
      'Yeni destek talebi',
      format('Yeni bir destek talebi geldi: %s', v_subject),
      format('/admin/support/%s', v_ticket_id),
      p_related_job_id,
      current_user_id,
      null,
      null,
      null,
      null,
      jsonb_build_object(
        'ticket_id', v_ticket_id,
        'category', p_category,
        'priority', v_priority
      )
    from public.profiles as profile
    where profile.is_admin = true;
  exception
    when others then
      raise warning 'admin support notifications failed: %', sqlerrm;
  end;

  return v_ticket_id;
end;
$$;

revoke all on function public.create_support_ticket(
  text, text, text, text, bigint
) from public, anon;

grant execute on function public.create_support_ticket(
  text, text, text, text, bigint
) to authenticated;
