-- Admin support tickets (phase 1: schema + user create RPC).
-- Does not change jobs, offers, reviews, messages, profiles,
-- complete_my_job, or admin_activity_events schema/triggers.

create table if not exists public.admin_support_tickets (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  user_id uuid not null references public.profiles (id),
  subject text not null,
  description text not null,
  category text not null,
  priority text not null default 'normal',
  status text not null default 'open',
  assigned_admin_id uuid null references public.profiles (id),
  related_job_id bigint null references public.jobs (id),
  resolved_at timestamptz null,
  constraint admin_support_tickets_subject_check
    check (char_length(btrim(subject)) > 0),
  constraint admin_support_tickets_description_check
    check (char_length(btrim(description)) > 0),
  constraint admin_support_tickets_category_check
    check (
      category in (
        'job',
        'offer',
        'messaging',
        'account',
        'payment',
        'technical',
        'other'
      )
    ),
  constraint admin_support_tickets_priority_check
    check (
      priority in ('low', 'normal', 'high', 'urgent')
    ),
  constraint admin_support_tickets_status_check
    check (
      status in ('open', 'in_progress', 'resolved', 'closed')
    )
);

create index if not exists admin_support_tickets_user_id_created_at_idx
  on public.admin_support_tickets (user_id, created_at desc);

create index if not exists admin_support_tickets_status_idx
  on public.admin_support_tickets (status);

create table if not exists public.admin_support_ticket_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  ticket_id bigint not null
    references public.admin_support_tickets (id)
    on delete cascade,
  sender_id uuid not null references public.profiles (id),
  message text not null,
  visibility text not null default 'user',
  constraint admin_support_ticket_messages_message_check
    check (char_length(btrim(message)) > 0),
  constraint admin_support_ticket_messages_visibility_check
    check (visibility in ('user', 'internal'))
);

create index if not exists admin_support_ticket_messages_ticket_id_created_at_idx
  on public.admin_support_ticket_messages (ticket_id, created_at);

create or replace function public.set_admin_support_tickets_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

revoke all on function public.set_admin_support_tickets_updated_at()
  from public, anon, authenticated;

drop trigger if exists admin_support_tickets_set_updated_at
  on public.admin_support_tickets;

create trigger admin_support_tickets_set_updated_at
  before update on public.admin_support_tickets
  for each row
  execute procedure public.set_admin_support_tickets_updated_at();

alter table public.admin_support_tickets enable row level security;
alter table public.admin_support_tickets force row level security;

alter table public.admin_support_ticket_messages enable row level security;
alter table public.admin_support_ticket_messages force row level security;

revoke all on table public.admin_support_tickets
  from public, anon, authenticated;

revoke all on table public.admin_support_ticket_messages
  from public, anon, authenticated;

grant select on table public.admin_support_tickets to authenticated;
grant select on table public.admin_support_ticket_messages to authenticated;

create policy admin_support_tickets_select_own
  on public.admin_support_tickets
  for select
  to authenticated
  using (user_id = auth.uid());

create policy admin_support_tickets_select_admin
  on public.admin_support_tickets
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.profiles as profile
      where profile.id = auth.uid()
        and profile.is_admin = true
    )
  );

create policy admin_support_ticket_messages_select_own_user
  on public.admin_support_ticket_messages
  for select
  to authenticated
  using (
    visibility = 'user'
    and exists (
      select 1
      from public.admin_support_tickets as ticket
      where ticket.id = admin_support_ticket_messages.ticket_id
        and ticket.user_id = auth.uid()
    )
  );

create policy admin_support_ticket_messages_select_admin
  on public.admin_support_ticket_messages
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.profiles as profile
      where profile.id = auth.uid()
        and profile.is_admin = true
    )
  );

create or replace function public.create_support_ticket(
  p_subject text,
  p_description text,
  p_category text,
  p_priority text default 'normal',
  p_related_job_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  v_subject text;
  v_description text;
  v_priority text;
  v_actor_role text;
  v_ticket_id bigint;
begin
  if current_user_id is null then
    raise exception 'Giriş yapmalısın.';
  end if;

  v_subject := nullif(btrim(coalesce(p_subject, '')), '');
  v_description := nullif(btrim(coalesce(p_description, '')), '');
  v_priority := coalesce(nullif(btrim(coalesce(p_priority, '')), ''), 'normal');

  if v_subject is null then
    raise exception 'Konu boş olamaz.';
  end if;

  if v_description is null then
    raise exception 'Açıklama boş olamaz.';
  end if;

  if p_category is null or p_category not in (
    'job',
    'offer',
    'messaging',
    'account',
    'payment',
    'technical',
    'other'
  ) then
    raise exception 'Geçerli bir kategori seç.';
  end if;

  if v_priority not in ('low', 'normal', 'high', 'urgent') then
    raise exception 'Geçerli bir öncelik seç.';
  end if;

  if p_related_job_id is not null then
    if not exists (
      select 1
      from public.jobs as job
      where job.id = p_related_job_id
    ) then
      raise exception 'İlgili iş bulunamadı.';
    end if;
  end if;

  insert into public.admin_support_tickets (
    user_id,
    subject,
    description,
    category,
    priority,
    status,
    related_job_id
  ) values (
    current_user_id,
    v_subject,
    v_description,
    p_category,
    v_priority,
    'open',
    p_related_job_id
  )
  returning id into v_ticket_id;

  select case
    when profile.provider_enabled and not profile.customer_enabled then 'provider'
    else 'customer'
  end
  into v_actor_role
  from public.profiles as profile
  where profile.id = current_user_id;

  perform public.log_activity_event(
    'support.ticket_created',
    v_actor_role,
    'support_ticket',
    v_ticket_id,
    null,
    p_related_job_id,
    jsonb_build_object(
      'category', p_category,
      'priority', v_priority,
      'status', 'open'
    )
  );

  return v_ticket_id;
end;
$$;

revoke all on function public.create_support_ticket(
  text, text, text, text, bigint
) from public, anon;

grant execute on function public.create_support_ticket(
  text, text, text, text, bigint
) to authenticated;
