-- New table: public.reviews
-- One review per completed job, written by the job's customer
-- about the accepted offer's provider.
-- SELECT for authenticated. INSERT gated by WITH CHECK.
-- No UPDATE/DELETE policies (MVP). Does not alter jobs, offers,
-- profiles, provider_profiles, or existing RLS/RPCs.

create table public.reviews (
  id bigint generated by default as identity primary key,
  job_id bigint not null
    references public.jobs (id)
    on delete cascade,
  provider_id uuid not null
    references public.profiles (id)
    on delete cascade,
  customer_id uuid not null
    references public.profiles (id)
    on delete cascade,
  rating integer not null
    check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamptz not null default now(),
  unique (job_id),
  check (provider_id <> customer_id)
);

create index reviews_provider_id_idx
  on public.reviews (provider_id);

create index reviews_customer_id_idx
  on public.reviews (customer_id);

alter table public.reviews enable row level security;

grant select, insert
  on public.reviews
  to authenticated;

grant usage, select
  on sequence public.reviews_id_seq
  to authenticated;

create policy reviews_select
  on public.reviews
  for select
  to authenticated
  using (true);

create policy reviews_insert
  on public.reviews
  for insert
  to authenticated
  with check (
    auth.uid() = customer_id
    and provider_id <> customer_id
    and exists (
      select 1
      from public.jobs as job
      where job.id = reviews.job_id
        and job.customer_id = auth.uid()
        and job.status = 'completed'
    )
    and exists (
      select 1
      from public.offers as offer
      where offer.job_id = reviews.job_id
        and offer.status = 'accepted'
        and offer.provider_id = reviews.provider_id
    )
  );
