-- Convert job-scoped conversations into one conversation per user pair.
-- Does not delete messages. Does not change notification trigger types.
-- Does not apply itself; review before running on live.
-- Old conversations/messages RLS policies that reference conversations.job_id
-- must be dropped before DROP COLUMN job_id (no CASCADE).

-- ---------------------------------------------------------------------------
-- 1. New tables and messages.job_id
-- ---------------------------------------------------------------------------

create table if not exists public.conversation_jobs (
  conversation_id bigint not null
    references public.conversations (id)
    on delete cascade,
  job_id bigint not null
    references public.jobs (id)
    on delete cascade,
  created_at timestamptz not null default now(),
  primary key (conversation_id, job_id),
  unique (job_id)
);

create table if not exists public.conversation_events (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null
    references public.conversations (id)
    on delete cascade,
  job_id bigint not null
    references public.jobs (id)
    on delete cascade,
  type text not null
    check (
      type in (
        'offer_sent',
        'offer_accepted',
        'offer_rejected',
        'job_created',
        'job_completed',
        'job_cancelled'
      )
    ),
  actor_id uuid null
    references public.profiles (id)
    on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists conversation_events_conversation_created_idx
  on public.conversation_events (conversation_id, created_at);

create table if not exists public.conversation_migration_map (
  old_conversation_id bigint primary key,
  canonical_conversation_id bigint not null,
  job_id bigint,
  participant_low uuid,
  participant_high uuid
);

alter table public.messages
  add column if not exists job_id bigint
    references public.jobs (id)
    on delete set null;

alter table public.conversations
  add column if not exists participant_low uuid;

alter table public.conversations
  add column if not exists participant_high uuid;

-- ---------------------------------------------------------------------------
-- 2. Validate source data before any merge
-- ---------------------------------------------------------------------------

do $$
declare
  null_job_count integer;
  multi_accepted text;
  missing_provider text;
  self_pair_count integer;
begin
  select count(*)
  into null_job_count
  from public.conversations
  where job_id is null;

  if null_job_count > 0 then
    raise exception
      'Migration aborted: % conversation(s) have null job_id',
      null_job_count;
  end if;

  select string_agg(job_id::text, ', ' order by job_id)
  into multi_accepted
  from (
    select offer.job_id
    from public.offers as offer
    where offer.status = 'accepted'
    group by offer.job_id
    having count(*) > 1
  ) as duplicated;

  if multi_accepted is not null then
    raise exception
      'Migration aborted: multiple accepted offers on job_id(s): %',
      multi_accepted;
  end if;

  select string_agg(conversation.id::text, ', ' order by conversation.id)
  into missing_provider
  from public.conversations as conversation
  where not exists (
    select 1
    from public.offers as offer
    where offer.job_id = conversation.job_id
      and offer.status = 'accepted'
  );

  if missing_provider is not null then
    raise exception
      'Migration aborted: no accepted provider for conversation id(s): %',
      missing_provider;
  end if;

  select count(*)
  into self_pair_count
  from public.conversations as conversation
  inner join public.jobs as job
    on job.id = conversation.job_id
  inner join public.offers as offer
    on offer.job_id = job.id
    and offer.status = 'accepted'
  where job.customer_id = offer.provider_id;

  if self_pair_count > 0 then
    raise exception
      'Migration aborted: % conversation(s) would have participant_low = participant_high',
      self_pair_count;
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 3. Backfill participants and messages.job_id
-- ---------------------------------------------------------------------------

update public.conversations as conversation
set
  participant_low = least(job.customer_id, offer.provider_id),
  participant_high = greatest(job.customer_id, offer.provider_id)
from public.jobs as job
inner join public.offers as offer
  on offer.job_id = job.id
  and offer.status = 'accepted'
where job.id = conversation.job_id;

do $$
declare
  unset_count integer;
begin
  select count(*)
  into unset_count
  from public.conversations
  where participant_low is null
     or participant_high is null;

  if unset_count > 0 then
    raise exception
      'Migration aborted: % conversation(s) still missing participants',
      unset_count;
  end if;
end
$$;

update public.messages as message
set job_id = conversation.job_id
from public.conversations as conversation
where message.conversation_id = conversation.id
  and conversation.job_id is not null
  and message.job_id is null;

-- ---------------------------------------------------------------------------
-- 4. Mapping + canonical = min(id) per pair
-- ---------------------------------------------------------------------------

truncate public.conversation_migration_map;

insert into public.conversation_migration_map (
  old_conversation_id,
  canonical_conversation_id,
  job_id,
  participant_low,
  participant_high
)
select
  conversation.id,
  min(conversation.id) over (
    partition by
      conversation.participant_low,
      conversation.participant_high
  ),
  conversation.job_id,
  conversation.participant_low,
  conversation.participant_high
from public.conversations as conversation;

-- ---------------------------------------------------------------------------
-- 5. Move messages to canonical conversations (ids unchanged)
-- ---------------------------------------------------------------------------

update public.messages as message
set conversation_id = migration_map.canonical_conversation_id
from public.conversation_migration_map as migration_map
where message.conversation_id = migration_map.old_conversation_id
  and migration_map.old_conversation_id
    <> migration_map.canonical_conversation_id;

do $$
declare
  leftover integer;
begin
  select count(*)
  into leftover
  from public.messages as message
  inner join public.conversation_migration_map as migration_map
    on migration_map.old_conversation_id = message.conversation_id
  where migration_map.old_conversation_id
    <> migration_map.canonical_conversation_id;

  if leftover > 0 then
    raise exception
      'Migration aborted: % message(s) still on duplicate conversations',
      leftover;
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 6. conversation_jobs from every old conversation.job_id
-- ---------------------------------------------------------------------------

insert into public.conversation_jobs (
  conversation_id,
  job_id
)
select distinct
  migration_map.canonical_conversation_id,
  migration_map.job_id
from public.conversation_migration_map as migration_map
where migration_map.job_id is not null
on conflict (job_id) do nothing;

-- ---------------------------------------------------------------------------
-- 7. conversation_reads: MIN cursor, null stays null
-- ---------------------------------------------------------------------------

insert into public.conversation_reads (
  conversation_id,
  user_id,
  last_read_message_id,
  updated_at
)
select
  migration_map.canonical_conversation_id,
  conversation_read.user_id,
  case
    when bool_or(conversation_read.last_read_message_id is null)
      then null
    else min(conversation_read.last_read_message_id)
  end,
  max(conversation_read.updated_at)
from public.conversation_reads as conversation_read
inner join public.conversation_migration_map as migration_map
  on migration_map.old_conversation_id = conversation_read.conversation_id
group by
  migration_map.canonical_conversation_id,
  conversation_read.user_id
on conflict (conversation_id, user_id)
do update set
  last_read_message_id = excluded.last_read_message_id,
  updated_at = excluded.updated_at;

delete from public.conversation_reads as conversation_read
using public.conversation_migration_map as migration_map
where conversation_read.conversation_id =
    migration_map.old_conversation_id
  and migration_map.old_conversation_id <>
    migration_map.canonical_conversation_id;

-- ---------------------------------------------------------------------------
-- 8. notifications.conversation_id → canonical (types unchanged)
-- ---------------------------------------------------------------------------

update public.notifications as notification
set conversation_id = migration_map.canonical_conversation_id
from public.conversation_migration_map as migration_map
where notification.conversation_id = migration_map.old_conversation_id
  and migration_map.old_conversation_id
    <> migration_map.canonical_conversation_id;

-- ---------------------------------------------------------------------------
-- 9. Remove duplicate conversation rows (messages already moved)
-- ---------------------------------------------------------------------------

do $$
declare
  message_count_before integer;
  message_count_after integer;
begin
  select count(*) into message_count_before from public.messages;

  delete from public.conversations as conversation
  using public.conversation_migration_map as migration_map
  where conversation.id = migration_map.old_conversation_id
    and migration_map.old_conversation_id
      <> migration_map.canonical_conversation_id;

  select count(*) into message_count_after from public.messages;

  if message_count_after <> message_count_before then
    raise exception
      'Migration aborted: message count changed from % to %',
      message_count_before,
      message_count_after;
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 10. Harden conversations columns, unique pair, drop job_id
-- ---------------------------------------------------------------------------

alter table public.conversations
  alter column participant_low set not null;

alter table public.conversations
  alter column participant_high set not null;

alter table public.conversations
  drop constraint if exists conversations_participants_order;

alter table public.conversations
  add constraint conversations_participants_order
  check (participant_low < participant_high);

alter table public.conversations
  drop constraint if exists conversations_participants_distinct;

alter table public.conversations
  add constraint conversations_participants_distinct
  check (participant_low <> participant_high);

alter table public.conversations
  drop constraint if exists conversations_participant_low_fkey;

alter table public.conversations
  add constraint conversations_participant_low_fkey
  foreign key (participant_low)
  references public.profiles (id);

alter table public.conversations
  drop constraint if exists conversations_participant_high_fkey;

alter table public.conversations
  add constraint conversations_participant_high_fkey
  foreign key (participant_high)
  references public.profiles (id);

create unique index if not exists conversations_participants_uidx
  on public.conversations (participant_low, participant_high);

-- Drop job_id-dependent RLS before dropping conversations.job_id.
do $$
declare
  policy_row record;
begin
  for policy_row in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'conversations'
  loop
    execute format(
      'drop policy if exists %I on public.conversations',
      policy_row.policyname
    );
  end loop;

  for policy_row in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'messages'
  loop
    execute format(
      'drop policy if exists %I on public.messages',
      policy_row.policyname
    );
  end loop;
end
$$;

alter table public.conversations
  drop column if exists job_id;

-- ---------------------------------------------------------------------------
-- 11. RPCs
-- ---------------------------------------------------------------------------

create or replace function public.can_access_conversation(
  p_conversation_id bigint
)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    return false;
  end if;

  return exists (
    select 1
    from public.conversations as conversation
    where conversation.id = p_conversation_id
      and current_user_id in (
        conversation.participant_low,
        conversation.participant_high
      )
      and exists (
        select 1
        from public.conversation_jobs as conversation_job
        inner join public.jobs as job
          on job.id = conversation_job.job_id
        where conversation_job.conversation_id = conversation.id
          and (
            job.customer_id = current_user_id
            or exists (
              select 1
              from public.offers as offer
              where offer.job_id = job.id
                and offer.status = 'accepted'
                and offer.provider_id = current_user_id
            )
          )
      )
  );
end;
$$;

create or replace function public.get_or_create_conversation(
  p_job_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  job_customer_id uuid;
  job_provider_id uuid;
  pair_low uuid;
  pair_high uuid;
  conversation_id bigint;
begin
  if current_user_id is null then
    raise exception 'Oturum bulunamadı.';
  end if;

  select job.customer_id
  into job_customer_id
  from public.jobs as job
  where job.id = p_job_id;

  if job_customer_id is null then
    raise exception 'İş bulunamadı.';
  end if;

  select offer.provider_id
  into job_provider_id
  from public.offers as offer
  where offer.job_id = p_job_id
    and offer.status = 'accepted';

  if job_provider_id is null then
    raise exception 'Sohbet için kabul edilmiş uzman yok.';
  end if;

  if job_customer_id = job_provider_id then
    raise exception 'Sohbet oluşturulamadı.';
  end if;

  if current_user_id is distinct from job_customer_id
    and current_user_id is distinct from job_provider_id
  then
    raise exception 'Bu konuşmaya erişim yetkiniz yok.';
  end if;

  pair_low := least(job_customer_id, job_provider_id);
  pair_high := greatest(job_customer_id, job_provider_id);

  insert into public.conversations (
    participant_low,
    participant_high
  )
  values (
    pair_low,
    pair_high
  )
  on conflict (participant_low, participant_high)
  do update set
    created_at = public.conversations.created_at
  returning id
  into conversation_id;

  insert into public.conversation_jobs (
    conversation_id,
    job_id
  )
  values (
    conversation_id,
    p_job_id
  )
  on conflict (job_id) do nothing;

  return conversation_id;
end;
$$;

create or replace function public.send_message(
  p_conversation_id bigint,
  p_message text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  message_id bigint;
begin
  if current_user_id is null then
    raise exception 'Oturum bulunamadı.';
  end if;

  if coalesce(nullif(btrim(p_message), ''), '') = '' then
    raise exception 'Boş mesaj gönderilemez.';
  end if;

  if coalesce(
    public.can_access_conversation(p_conversation_id),
    false
  ) is not true then
    raise exception 'Bu konuşmaya erişim yetkiniz yok.';
  end if;

  insert into public.messages (
    conversation_id,
    sender_id,
    message
  )
  values (
    p_conversation_id,
    current_user_id,
    p_message
  )
  returning id into message_id;

  return message_id;
end;
$$;

create or replace function public.get_my_conversations()
returns table (
  conversation_id bigint,
  job_id bigint,
  job_title text,
  other_user_id uuid,
  other_user_name text,
  last_message text,
  last_message_at timestamptz,
  unread_count integer
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Oturum bulunamadı.';
  end if;

  return query
  select
    conversation.id,
    latest_job.id,
    latest_job.title,
    case
      when conversation.participant_low = current_user_id
        then conversation.participant_high
      else conversation.participant_low
    end,
    nullif(btrim(other_profile.full_name), ''),
    last_msg.message,
    coalesce(last_msg.created_at, conversation.created_at),
    (
      select count(*)::integer
      from public.messages as unread_message
      where unread_message.conversation_id = conversation.id
        and unread_message.sender_id <> current_user_id
        and (
          conversation_read.last_read_message_id is null
          or unread_message.id > conversation_read.last_read_message_id
        )
    )
  from public.conversations as conversation
  left join lateral (
    select job.id, job.title
    from public.conversation_jobs as conversation_job
    inner join public.jobs as job
      on job.id = conversation_job.job_id
    where conversation_job.conversation_id = conversation.id
    order by conversation_job.created_at desc, job.id desc
    limit 1
  ) as latest_job on true
  left join lateral (
    select msg.message, msg.created_at
    from public.messages as msg
    where msg.conversation_id = conversation.id
    order by msg.created_at desc, msg.id desc
    limit 1
  ) as last_msg on true
  left join public.conversation_reads as conversation_read
    on conversation_read.conversation_id = conversation.id
    and conversation_read.user_id = current_user_id
  left join public.profiles as other_profile
    on other_profile.id = case
      when conversation.participant_low = current_user_id
        then conversation.participant_high
      else conversation.participant_low
    end
  where public.can_access_conversation(conversation.id)
  order by coalesce(last_msg.created_at, conversation.created_at) desc;
end;
$$;

-- mark_conversation_read: body already uses can_access + max(messages.id).
-- Recreate only to keep grants explicit; logic unchanged.

create or replace function public.mark_conversation_read(
  p_conversation_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  latest_message_id bigint;
begin
  if current_user_id is null then
    raise exception 'Oturum bulunamadı.';
  end if;

  if coalesce(
    public.can_access_conversation(p_conversation_id),
    false
  ) is not true then
    raise exception 'Bu konuşmaya erişim yetkiniz yok.';
  end if;

  select max(message.id)
  into latest_message_id
  from public.messages as message
  where message.conversation_id = p_conversation_id;

  insert into public.conversation_reads (
    conversation_id,
    user_id,
    last_read_message_id,
    updated_at
  )
  values (
    p_conversation_id,
    current_user_id,
    latest_message_id,
    now()
  )
  on conflict (conversation_id, user_id)
  do update set
    last_read_message_id = excluded.last_read_message_id,
    updated_at = now();
end;
$$;

revoke all on function public.can_access_conversation(bigint) from public;
revoke all on function public.can_access_conversation(bigint) from anon;
grant execute on function public.can_access_conversation(bigint) to authenticated;

revoke all on function public.get_or_create_conversation(bigint) from public;
revoke all on function public.get_or_create_conversation(bigint) from anon;
grant execute on function public.get_or_create_conversation(bigint) to authenticated;

revoke all on function public.send_message(bigint, text) from public;
revoke all on function public.send_message(bigint, text) from anon;
grant execute on function public.send_message(bigint, text) to authenticated;

revoke all on function public.get_my_conversations() from public;
revoke all on function public.get_my_conversations() from anon;
grant execute on function public.get_my_conversations() to authenticated;

revoke all on function public.mark_conversation_read(bigint) from public;
revoke all on function public.mark_conversation_read(bigint) from anon;
grant execute on function public.mark_conversation_read(bigint) to authenticated;

-- ---------------------------------------------------------------------------
-- 12. RLS
-- ---------------------------------------------------------------------------

alter table public.conversation_jobs enable row level security;
alter table public.conversation_events enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.conversation_migration_map enable row level security;

revoke all on table public.conversation_jobs from public, anon, authenticated;
revoke all on table public.conversation_events from public, anon, authenticated;
revoke all on table public.conversation_migration_map from public, anon, authenticated;

grant select on table public.conversation_jobs to authenticated;
grant select on table public.conversation_events to authenticated;
grant select on table public.conversations to authenticated;
grant select on table public.messages to authenticated;

create policy conversations_select_access
  on public.conversations
  for select
  to authenticated
  using (public.can_access_conversation(id));

create policy messages_select_access
  on public.messages
  for select
  to authenticated
  using (public.can_access_conversation(conversation_id));

create policy conversation_jobs_select_access
  on public.conversation_jobs
  for select
  to authenticated
  using (
    public.can_access_conversation(conversation_id)
    and (
      exists (
        select 1
        from public.jobs as job
        where job.id = conversation_jobs.job_id
          and job.customer_id = auth.uid()
      )
      or exists (
        select 1
        from public.offers as offer
        where offer.job_id = conversation_jobs.job_id
          and offer.status = 'accepted'
          and offer.provider_id = auth.uid()
      )
    )
  );

create policy conversation_events_select_access
  on public.conversation_events
  for select
  to authenticated
  using (public.can_access_conversation(conversation_id));

-- conversation_reads: keep existing own-row SELECT; writes stay on RPC.

do $$
declare
  conversation_count integer;
  pair_count integer;
  mapped_jobs integer;
  linked_jobs integer;
begin
  select count(*) into conversation_count from public.conversations;
  select count(*) into pair_count
  from (
    select participant_low, participant_high
    from public.conversations
    group by participant_low, participant_high
  ) as pairs;

  if conversation_count <> pair_count then
    raise exception
      'Migration aborted: conversation count % != unique pair count %',
      conversation_count,
      pair_count;
  end if;

  select count(distinct job_id)
  into mapped_jobs
  from public.conversation_migration_map
  where job_id is not null;

  select count(*)
  into linked_jobs
  from public.conversation_jobs;

  if linked_jobs <> mapped_jobs then
    raise exception
      'Migration aborted: conversation_jobs % != mapped jobs %',
      linked_jobs,
      mapped_jobs;
  end if;

  if exists (
    select 1
    from public.conversation_migration_map as migration_map
    where migration_map.job_id is not null
      and not exists (
        select 1
        from public.conversation_jobs as conversation_job
        where conversation_job.job_id = migration_map.job_id
          and conversation_job.conversation_id
            = migration_map.canonical_conversation_id
      )
  ) then
    raise exception
      'Migration aborted: conversation_jobs mapping mismatch';
  end if;

  if exists (
    select 1
    from (
      select distinct
        migration_map.job_id,
        migration_map.canonical_conversation_id
      from public.conversation_migration_map as migration_map
      where migration_map.job_id is not null
    ) as expected_job
    where (
      select count(*)
      from public.conversation_jobs as conversation_job
      where conversation_job.job_id = expected_job.job_id
    ) <> 1
    or not exists (
      select 1
      from public.conversation_jobs as conversation_job
      where conversation_job.job_id = expected_job.job_id
        and conversation_job.conversation_id
          = expected_job.canonical_conversation_id
    )
  ) then
    raise exception
      'Migration aborted: conversation_jobs mapping mismatch';
  end if;
end
$$;
